version: '3'

services:

  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=hadoop-cluster
    env_file:
      - ./hadoop.env
    volumes:
      - namenode_data:/hadoop/dfs/name

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode
    depends_on:
      - hadoop-namenode
    ports:
      - "9864:9864"
    env_file:
      - ./hadoop.env
    volumes:
      - datanode_data:/hadoop/dfs/data

  hadoop-resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-resourcemanager
    depends_on:
      - hadoop-namenode
    ports:
      - "8088:8088"
    env_file:
      - ./hadoop.env

  hadoop-nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-nodemanager
    depends_on:
      - hadoop-resourcemanager
    env_file:
      - ./hadoop.env

  hadoop-historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-historyserver
    depends_on:
      - hadoop-resourcemanager
    ports:
      - "8188:8188"
    env_file:
      - ./hadoop.env

volumes:
  namenode_data:
  datanode_data: